server:
  port: 8081
spring:
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      port: 6379
      host: localhost
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis

--- ## –î–ê–ù–ù–´–ï –û –ë–û–¢–ï ##

BOT_LOGIN: "@GorodX_HMAO_bot"
BOT_TOKEN: "7910888745:AAH1Pr_ZpBUETfWEtBu7OUqZgE4JIE9uX08"

--- ## C–û–û–ë–©–ï–ù–ò–Ø ##

#REGISTRATION
ASK_NAME: –ö–∞–∫ —Ç–µ–±—è –∑–æ–≤—É—Ç?
ASK_AGE: –°–∫–æ–ª—å–∫–æ —Ç–µ–±–µ –ª–µ—Ç?
ASK_CITY: –û—Ç–∫—É–¥–∞ —Ç—ã?
ASK_ABOUT_ME: –ú–æ–∂–µ—à—å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ —Ä–∞—Å—Å–∫–∞–∑–∞—Ç—å –æ —Å–µ–±–µ, –∏–ª–∏ –æ —Ç–æ–º, –∫–æ–≥–æ —Ö–æ—á–µ—à—å –Ω–∞–π—Ç–∏
ASK_AVATAR: –î–∞–≤–∞–π –∑–∞–≥—Ä—É–∑–∏–º –∞–≤–∞—Ç–∞—Ä–∫–∏ –¥–ª—è —Ç–≤–æ–µ–π –∞–Ω–∫–µ—Ç—ã. –û—Ç–ø—Ä–∞–≤–ª—è–π –ø–æ–æ—á–µ—Ä–µ–¥–Ω–æ —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏–∏ –∏–ª–∏ –≤–∏–¥–µ–æ, –º–æ–∂–Ω–æ –∑–∞–≥—Ä—É–∑–∏—Ç—å –Ω–µ –±–æ–ª–µ–µ 3-—Ö —Ñ–∞–π–ª–æ–≤
RESULT: –í–æ—Ç —Ç–≤–æ—è –∞–Ω–∫–µ—Ç–∞

#EDIT
EDIT_NAME: –í–≤–µ–¥–∏ –Ω–æ–≤–æ–µ –∏–º—è
EDIT_AGE: –í–≤–µ–¥–∏ –Ω–æ–≤—ã–π –≤–æ–∑—Ä–∞—Å—Ç
EDIT_CITY: –í—ã–±–µ—Ä–∏ –Ω–æ–≤–æ–µ –º–µ—Å—Ç–æ–ø–æ–ª–æ–∂–µ–Ω–∏–µ
EDIT_PHOTO: –û—Ç–ø—Ä–∞–≤–ª—è–π –ø–æ–æ—á–µ—Ä–µ–¥–Ω–æ –Ω–æ–≤—ã–µ —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏–∏ –∏–ª–∏ –≤–∏–¥–µ–æ –¥–ª—è —Å–≤–æ–µ–π –∞–Ω–∫–µ—Ç—ã, –º–æ–∂–Ω–æ –∑–∞–≥—Ä—É–∑–∏—Ç—å –Ω–µ –±–æ–ª–µ–µ 3-—ë—Ö —Ñ–∞–π–ª–æ–≤
EDIT_RESULT: –¢–∞–∫ –±—É–¥–µ—Ç –≤—ã–≥–ª—è–¥–µ—Ç—å —Ç–≤–æ—è –∞–Ω–∫–µ—Ç–∞
NULL_DATA_EDIT: –í—ã –Ω–∏—á–µ–≥–æ –Ω–µ –∏–∑–º–µ–Ω–∏–ª–∏, –≤–æ–∑–≤—Ä–∞—â–∞–µ–º—Å—è –≤ –ø—Ä–æ—Ñ–∏–ª—å
STOP_ADD_AVATAR: –ì–æ—Ç–æ–≤–æ
SKIP_ADD_AVATAR: –ù–µ –∏–∑–º–µ–Ω—è—Ç—å

#MENU
MENU:
  1. –ù–∞—á–∞—Ç—å –ø–æ–∏—Å–∫ ‚ú®
  
  2. –ú–æ—è –∞–Ω–∫–µ—Ç–∞
  
  3. –í—ã–∫–ª—é—á–∏—Ç—å –∞–Ω–∫–µ—Ç—É
MY_PROFILE: –í—ã–±–µ—Ä–∏ —á—Ç–æ —Ö–æ—á–µ—à—å –∏–∑–º–µ–Ω–∏—Ç—å

#LEFT GROUP OR DISABLE PROFILE
ASK_BEFORE_OFF: –¢—ã —É–≤–µ—Ä–µ–Ω–∞, —á—Ç–æ —Ö–æ—á–µ—à—å –æ—Ç–∫–ª—é—á–∏—Ç—å —Å–≤–æ—é –∞–Ω–∫–µ—Ç—É?
LEFT: –ù–∞–º –æ—á–µ–Ω—å –∂–∞–ª—å, —á—Ç–æ —Ç—ã —É—Ö–æ–¥–∏—à—å. –ù–∞–¥–µ—é—Å—å, —É–≤–∏–¥–∏–º—Å—è —Å–Ω–æ–≤–∞!

#COMMANDS
FAQ:
  FAQ
  
  1. –ü–æ—á–µ–º—É –º–Ω–µ –ø–æ–ø–∞–¥–∞—é—Ç—Å—è –∞–Ω–∫–µ—Ç—ã –Ω–µ –∏–∑ –º–æ–µ–≥–æ –Ω–∞—Å–µ–ª—ë–Ω–Ω–æ–≥–æ –ø—É–Ω–∫—Ç–∞?
  
  2. –í –ø–æ—Å–ª–µ–¥–Ω–µ–µ –≤—Ä–µ–º—è –º–µ–Ω—è –Ω–µ –ª–∞–π–∫–∞—é—Ç –∏ –Ω–µ –æ—Ç–≤–µ—á–∞—é—Ç –≤–∑–∞–∏–º–Ω–æ—Å—Ç—å—é, –ø–æ—á–µ–º—É?
FAQ_1:
  –ó–¥–µ—Å—å –º–æ–∂–µ—Ç –±—ã—Ç—å –Ω–µ—Å–∫–æ–ª—å–∫–æ –ø—Ä–∏—á–∏–Ω.
  
  1. –ü—Ä–æ–≤–µ—Ä—å—Ç–µ, –≤–µ—Ä–Ω–æ –ª–∏ —É–∫–∞–∑–∞–Ω –≤–∞—à –Ω–∞—Å–µ–ª—ë–Ω–Ω—ã–π –ø—É–Ω–∫—Ç –≤ –∞–Ω–∫–µ—Ç–µ. 
  –•–æ—Ç—è –º—ã –∏—Å–ø–æ–ª—å–∑—É–µ–º –ª—É—á—à–∏–µ –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç—ã –¥–ª—è –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏—è –ª–æ–∫–∞—Ü–∏–∏, –≤—Å—ë —Ä–∞–≤–Ω–æ –º–æ–≥—É—Ç –ø—Ä–æ–∏—Å—Ö–æ–¥–∏—Ç—å —Å–±–æ–∏. 
  –ï—Å–ª–∏ –Ω–∞–∑–≤–∞–Ω–∏–µ –≤–∞—à–µ–≥–æ –Ω–∞—Å—ë–ª–µ–Ω–Ω–æ–≥–æ –ø—É–Ω–∫—Ç–∞ –∏–º–µ–µ—Ç —Å—Ö–æ–¥—Å—Ç–≤–æ —Å –¥—Ä—É–≥–∏–º–∏ –∫—Ä—É–ø–Ω—ã–º–∏ –Ω–∞—Å–µ–ª—ë–Ω–Ω—ã–º–∏ –ø—É–Ω–∫—Ç–∞–º–∏, —Ç–æ —Ä–µ–∫–æ–º–µ–Ω–¥—É–µ–º —É—Ç–æ—á–Ω–∏—Ç—å –æ–±–ª–∞—Å—Ç—å.

  2. –í–æ–∑–º–æ–∂–Ω–æ –∞–Ω–∫–µ—Ç—ã –∏–∑ –≤–∞—à–µ–≥–æ –≥–æ—Ä–æ–¥–∞ –∑–∞–∫–æ–Ω—á–∏–ª–∏—Å—å –∏ –±–æ—Ç –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –Ω–∞—á–∏–Ω–∞–µ—Ç —Ä–µ–∫–æ–º–µ–Ω–¥–æ–≤–∞—Ç—å –±–ª–∏–∂–∞–π—à–∏—Ö –∫ –≤–∞–º –ª—é–¥–µ–π –∏–∑ –¥—Ä—É–≥–∏—Ö –Ω–∞—Å–µ–ª—ë–Ω–Ω—ã—Ö –ø—É–Ω–∫—Ç–æ–≤. 
  –°–ø–∏—Å–æ–∫ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–π –æ–±–Ω–æ–≤–ª—è–µ—Ç—Å—è –≤ —Ç–µ—á–µ–Ω–∏–µ 24 —á–∞—Å–æ–≤
FAQ_2:
  –†–µ–∫–æ–º–µ–Ω–¥—É–µ–º —Å–¥–µ–ª–∞—Ç—å –≤–∞—à—É –∞–Ω–∫–µ—Ç—É –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ–π - –Ω–µ –ø–∏—à–∏—Ç–µ —Å–ª–∏—à–∫–æ–º –º–Ω–æ–≥–æ, –Ω–æ –∏ –Ω–µ —Å–ª–∏—à–∫–æ–º –º–∞–ª–æ. –ü–æ–º–Ω–∏—Ç–µ, —á—Ç–æ –Ω–∞ –æ—Å–Ω–æ–≤–∞–Ω–∏–∏ –≤–∞—à–µ–π –∞–Ω–∫–µ—Ç—ã —É —á–µ–ª–æ–≤–µ–∫–∞ —Å—Ñ–æ—Ä–º–∏—Ä—É–µ—Ç—Å—è –ø–µ—Ä–≤–æ–µ –º–Ω–µ–Ω–∏–µ.
  –í –¥—Ä—É–≥–∏—Ö —Å–∏—Ç—É–∞—Ü–∏—è—Ö, –µ—Å–ª–∏ –Ω–∞ –≤–∞—Å –±—ã–ª–æ –ø–æ–¥–∞–Ω–æ –º–Ω–æ–≥–æ –∂–∞–ª–æ–± –∏ –æ–Ω–∏ –ø–æ–¥—Ç–≤–µ—Ä–¥–∏–ª–∏—Å—å —Å–æ —Å—Ç–æ—Ä–æ–Ω—ã –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏ - –≤—ã –º–æ–≥–ª–∏ –ø–æ–ø–∞—Å—Ç—å –≤ –±–ª–æ–∫–∏—Ä–æ–≤–∫—É.
SEND_COMPLAINT: –í—ã —Å–æ–±–∏—Ä–∞–µ—Ç–µ—Å—å –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –∂–∞–ª–æ–±—É. –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ–ø–∏—à–∏—Ç–µ –≤ –¥–µ—Ç–∞–ª—è—Ö –≤–∞—à—É –ø—Ä–µ—Ç–µ–Ω–∑–∏—é –∏ –º—ã –Ω–µ–º–µ–¥–ª–µ–Ω–Ω–æ –Ω–∞ –Ω–µ—ë –æ—Ç—Ä–µ–∞–≥–∏—Ä—É–µ–º
SUCCESS_SEND_COMPLAINT: –ñ–∞–ª–æ–±–∞ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω–∞, –º—ã –µ—ë –≤–Ω–∏–º–∞—Ç–µ–ª—å–Ω–æ –∏–∑—É—á–∏–º ü§ù
BLOCK: –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω
PEACE: –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –ø–æ–º–∏–ª–æ–≤–∞–Ω
SEND_ERROR: –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –æ–ø–∏—à–∏—Ç–µ –≤ –¥–µ—Ç–∞–ª—è—Ö –ø—Ä–æ–±–ª–µ–º—É —Å –∫–æ—Ç–æ—Ä–æ–π –≤—ã —Å—Ç–æ–ª–∫–Ω—É–ª–∏—Å—å
SUCCESS_SEND_ERROR: –ë–ª–∞–≥–æ–¥–∞—Ä–∏–º –∑–∞ —Å–æ—Ç—Ä—É–¥–Ω–∏—á–µ—Å—Ç–≤–æ! –ú—ã –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ —Ä–∞—Å—Å–º–æ—Ç—Ä–∏–º –≤–∞—à—É –ø—Ä–æ–±–ª–µ–º—É


#FIND_PEOPLES
SEND_LIKE_AND_MESSAGE: –ú–æ–∂–µ—à—å –æ—Ç–ø—Ä–∞–≤–∏—Ç—å —Ç–µ–∫—Å—Ç–æ–≤–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ, –∫—Ä—É–∂–æ–∫, –≥–æ–ª–æ—Å–æ–≤–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ, —Ñ–æ—Ç–æ –∏–ª–∏ –≤–∏–¥–µ–æ. –Ø –ø—Ä–∏—à–ª—é –µ–≥–æ —ç—Ç–æ–º—É —á–µ–ª–æ–≤–µ–∫—É

#EXCEPTIONS
INVALID_FORMAT_EXCEPTION: –§–æ—Ä–º–∞—Ç –æ—Ç–≤–µ—Ç–∞ –Ω–µ –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ—Ç—Å—è
IS_NOT_A_NUMBER_EXCEPTION: –ù–µ–æ–±—Ö–æ–¥–∏–º–æ —É–∫–∞–∑–∞—Ç—å —á–∏—Å–ª–æ

CITY_LIMIT_SYMBOLS_EXCEPTIONS: –°–æ–∫—Ä–∞—Ç–∏—Ç–µ –Ω–∞–∑–≤–∞–Ω–∏–µ –≥–æ—Ä–æ–¥–∞
AGE_LIMIT_SYMBOLS_EXCEPTIONS: –£–∫–∞–∂–∏—Ç–µ –∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π –≤–æ–∑—Ä–∞—Å—Ç
NAME_LIMIT_SYMBOLS_EXCEPTIONS: –°–ª–∏—à–∫–æ–º –¥–ª–∏–Ω–Ω–æ–µ –∏–º—è. –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, —Å–æ–∫—Ä–∞—Ç–∏—Ç–µ –µ–≥–æ
HOBBY_LIMIT_SYMBOLS_EXCEPTIONS: –í—ã –æ—á–µ–Ω—å –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–π –∏ —Ä–∞–∑–Ω–æ—Å—Ç–æ—Ä–æ–Ω–Ω–∏–π —á–µ–ª–æ–≤–µ–∫, –Ω–æ –ª—É—á—à–µ –±—É–¥–µ—Ç –Ω–∞–ø–∏—Å–∞—Ç—å —Ç–æ–ª—å–∫–æ –æ—Å–Ω–æ–≤–Ω—ã–µ —Ö–æ–±–±–∏
ABOUT_ME_LIMIT_SYMBOLS_EXCEPTIONS: –ö—Ä–∞—Ç–∫–æ—Å—Ç—å - —Å–µ—Å—Ç—Ä–∞ —Ç–∞–ª–∞–Ω—Ç–∞. –ß—Ç–æ–±—ã —Å–¥–µ–ª–∞—Ç—å –≤–∞—à—É –∞–Ω–∫–µ—Ç—É –±–æ–ª–µ–µ –ø—Ä–∏–≤–ª–µ–∫–∞—Ç–µ–ª—å–Ω–æ–π, –º—ã —Ä–µ–∫–æ–º–µ–Ω–¥—É–µ–º –≤–∞–º –Ω–µ–º–Ω–æ–≥–æ —Å–æ–∫—Ä–∞—Ç–∏—Ç—å —Ç–µ–∫—Å—Ç

NOT_REGISTER: –°–Ω–∞—á–∞–ª–∞ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞—Ç—å—Å—è
WAIT_TIME_OUT_EXCEPTION: –í—Ä–µ–º—è –æ–∂–∏–¥–∞–Ω–∏—è –∏—Å—Ç–µ–∫–ª–æ, –≤–æ–∑–≤—Ä–∞—â–∞–µ–º—Å—è –≤ –≥–ª–∞–≤–Ω–æ–µ –º–µ–Ω—é
ROLE_EXCEPTION: –í—ã –Ω–µ –∏–º–µ–µ—Ç–µ –ø—Ä–∞–≤ –æ—Ç–ø—Ä–∞–≤–ª—è—Ç—å –∂–∞–ª–æ–±—ã
NOT_ENOUGH: –ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –ø—Ä–∞–≤ –¥–ª—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∫–æ–º–∞–Ω–¥—ã
ERROR: –ü—Ä–æ–∏–∑–æ—à–ª–∞ –Ω–µ–ø—Ä–µ–¥–≤–∏–¥–µ–Ω–Ω–∞—è –æ—à–∏–±–∫–∞, –≤–æ–∑–≤—Ä–∞—â–∞–µ–º—Å—è –≤ –º–µ–Ω—é...